# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.x
        
    - name: Install depedencies
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Staticcheck
      run: staticcheck ./...
